version: '2.3.3'
services:
  reverse-proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  app2:
    build: /home/ubuntu/devop2/
    volumes:
      - .:/home/ubuntu/devop2/app
    ports:
      - "8081:8081"   
  app1:
    build: /home/ubuntu/devop/
    volumes:
      - .:/home/ubuntu/devop/app	    
    ports:
      - "8080:8080"
         
